<?php

use Illuminate\Database\Seeder;

class DeItemCacheTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('de_item_cache')->delete();

        \DB::table('de_item_cache')->insert(array (
            0 =>
            array (
                'id' => 318,
                'path' => 'dataexchange/3',
                'title' => '3',
                'hash' => 'c68f8e8b3d24db8e8418225172cc4298',
                'description' => NULL,
                'extension' => NULL,
                'user_id' => NULL,
                'department_id' => NULL,
                'counterparty_id' => NULL,
                'parent_id' => NULL,
                'size' => 0,
                'item_type_id' => NULL,
                'mime_type_id' => NULL,
                'storage_id' => 7,
                'is_shared' => 0,
                'mtime' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2018-05-04 14:33:43',
                'updated_at' => '2018-05-04 14:33:43',
            ),
            1 =>
            array (
                'id' => 319,
                'path' => 'dataexchange/3/data',
                'title' => 'data',
                'hash' => 'd612993125cd7e1c59fb8606f8d0a561',
                'description' => NULL,
                'extension' => NULL,
                'user_id' => NULL,
                'department_id' => NULL,
                'counterparty_id' => NULL,
                'parent_id' => 318,
                'size' => 0,
                'item_type_id' => NULL,
                'mime_type_id' => NULL,
                'storage_id' => 7,
                'is_shared' => 0,
                'mtime' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2018-05-04 14:33:43',
                'updated_at' => '2018-05-04 14:33:43',
            ),
            2 =>
            array (
                'id' => 320,
                'path' => 'user3',
                'title' => 'user3',
                'hash' => '037c691c5fb7e5cb4327165a19383a47',
                'description' => NULL,
                'extension' => NULL,
                'user_id' => NULL,
                'department_id' => NULL,
                'counterparty_id' => NULL,
                'parent_id' => NULL,
                'size' => 0,
                'item_type_id' => NULL,
                'mime_type_id' => NULL,
                'storage_id' => 7,
                'is_shared' => 0,
                'mtime' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2018-05-04 14:33:43',
                'updated_at' => '2018-05-04 14:33:43',
            ),
            3 =>
            array (
                'id' => 321,
                'path' => 'dataexchange/3/user3',
                'title' => 'user3',
                'hash' => 'b1b33190d0babcac54272739a0d811eb',
                'description' => NULL,
                'extension' => NULL,
                'user_id' => NULL,
                'department_id' => NULL,
                'counterparty_id' => NULL,
                'parent_id' => 318,
                'size' => 0,
                'item_type_id' => NULL,
                'mime_type_id' => NULL,
                'storage_id' => 7,
                'is_shared' => 0,
                'mtime' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2018-05-04 14:33:43',
                'updated_at' => '2018-05-04 14:33:43',
            ),
            4 =>
            array (
                'id' => 322,
                'path' => 'user3/22.pptx',
                'title' => '22.pptx',
                'hash' => 'a6d84a5af7f7a2af2451ce50d5ad7cf2',
                'description' => NULL,
                'extension' => 'pptx',
                'user_id' => 3,
                'department_id' => NULL,
                'counterparty_id' => NULL,
                'parent_id' => 320,
                'size' => 0,
                'item_type_id' => 3,
                'mime_type_id' => 360,
                'storage_id' => 7,
                'is_shared' => 0,
                'mtime' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2018-05-04 14:33:43',
                'updated_at' => '2018-05-04 14:33:43',
            ),
            5 =>
            array (
                'id' => 323,
                'path' => 'user3/dorin',
                'title' => 'dorin',
                'hash' => 'd46c72700c3fe4111e53ddd0d6bec6b7',
                'description' => NULL,
                'extension' => 'folder',
                'user_id' => 3,
                'department_id' => NULL,
                'counterparty_id' => NULL,
                'parent_id' => 320,
                'size' => 0,
                'item_type_id' => 2,
                'mime_type_id' => NULL,
                'storage_id' => 7,
                'is_shared' => 0,
                'mtime' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2018-05-04 14:33:43',
                'updated_at' => '2018-05-04 14:33:43',
            ),
            6 =>
            array (
                'id' => 324,
                'path' => 'user3/dorin1',
                'title' => 'dorin1',
                'hash' => '730ca6d173e23c1fbf294430a346765f',
                'description' => NULL,
                'extension' => 'folder',
                'user_id' => 3,
                'department_id' => NULL,
                'counterparty_id' => NULL,
                'parent_id' => 320,
                'size' => 0,
                'item_type_id' => 2,
                'mime_type_id' => NULL,
                'storage_id' => 7,
                'is_shared' => 0,
                'mtime' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2018-05-04 14:33:43',
                'updated_at' => '2018-05-04 14:33:43',
            ),
            7 =>
            array (
                'id' => 325,
                'path' => 'user3/dorin4',
                'title' => 'dorin4',
                'hash' => '2f3e57815926b636b388a65024be9e59',
                'description' => NULL,
                'extension' => 'folder',
                'user_id' => 3,
                'department_id' => NULL,
                'counterparty_id' => NULL,
                'parent_id' => 320,
                'size' => 0,
                'item_type_id' => 2,
                'mime_type_id' => NULL,
                'storage_id' => 7,
                'is_shared' => 0,
                'mtime' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2018-05-04 14:33:43',
                'updated_at' => '2018-05-04 14:33:43',
            ),
            8 =>
            array (
                'id' => 326,
                'path' => 'user3/New Text Document.txt',
                'title' => 'New Text Document.txt',
                'hash' => 'c01f248403c6a20f421d2df5912df8d7',
                'description' => NULL,
                'extension' => 'txt',
                'user_id' => 3,
                'department_id' => NULL,
                'counterparty_id' => NULL,
                'parent_id' => 320,
                'size' => 1164,
                'item_type_id' => 3,
                'mime_type_id' => 694,
                'storage_id' => 7,
                'is_shared' => 0,
                'mtime' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2018-05-04 14:33:43',
                'updated_at' => '2018-05-04 14:33:43',
            ),
        ));


    }
}
